// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0FZhef6khDumc_zCyvHacHtbhybHCINs',
    appId: '1:361162976405:web:253ab13819cb2abf05bf9c',
    messagingSenderId: '361162976405',
    projectId: 'mentraapp-ee125',
    authDomain: 'mentraapp-ee125.firebaseapp.com',
    storageBucket: 'mentraapp-ee125.firebasestorage.app',
    measurementId: 'G-KHHZJBP3Q2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXt0fZo0W9lF0uxwT5W6MOE247G-_yJZA',
    appId: '1:361162976405:android:cd72eb69d2b9032b05bf9c',
    messagingSenderId: '361162976405',
    projectId: 'mentraapp-ee125',
    storageBucket: 'mentraapp-ee125.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLcG1sVtvU8WHwNnkuDmIGb1v6dyCUIPw',
    appId: '1:361162976405:ios:824586739cc0883905bf9c',
    messagingSenderId: '361162976405',
    projectId: 'mentraapp-ee125',
    storageBucket: 'mentraapp-ee125.firebasestorage.app',
    iosBundleId: 'com.example.mentraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLcG1sVtvU8WHwNnkuDmIGb1v6dyCUIPw',
    appId: '1:361162976405:ios:824586739cc0883905bf9c',
    messagingSenderId: '361162976405',
    projectId: 'mentraapp-ee125',
    storageBucket: 'mentraapp-ee125.firebasestorage.app',
    iosBundleId: 'com.example.mentraApp',
  );
}
