import 'package:flutter/material.dart';
import 'package:mentra_app/pages/mood/mood_bar_chart.dart';
import 'package:mentra_app/pages/mood/mood_graph_bottom_nav.dart';
import 'package:mentra_app/pages/mood/mood_graph_styles.dart';
import 'package:mentra_app/pages/mood/mood_line_chart.dart';
import 'package:mentra_app/pages/mood/range_selector.dart';
import 'package:provider/provider.dart';
import 'package:mentra_app/providers/theme_provider.dart';
import 'package:mentra_app/services/mood_repository.dart';
import 'package:mentra_app/models/mood_data.dart';

// Modüller

class MoodGraphPage extends StatefulWidget {
  const MoodGraphPage({super.key});
  @override
  State<MoodGraphPage> createState() => _MoodGraphPageState();
}

class _MoodGraphPageState extends State<MoodGraphPage> {
  final MoodRepository _repo = MoodRepository();
  late Future<List<MoodData>> _future;
  MoodRange _range = MoodRange.week;

  @override
  void initState() {
    super.initState();
    _load();
  }

  void _load() => _future = _repo.fetchMoodTrend(_range);

  @override
  Widget build(BuildContext context) {
    final isDark = Provider.of<ThemeProvider>(context).isDarkMode;
    return Scaffold(
      appBar: AppBar(
        title: Text(
          'Mood Graph',
          style: TextStyle(
            color: MoodGraphStyles.getTextColor(isDark),
            fontWeight: FontWeight.w600,
          ),
        ),
        backgroundColor: isDark ? const Color(0xFF1E1E1E) : Colors.white,
        elevation: 0,
        iconTheme: IconThemeData(color: isDark ? Colors.white : Colors.black),
      ),
      body: Stack(
        children: [
          Container(
            decoration: BoxDecoration(
              gradient: MoodGraphStyles.getBackground(isDark),
            ),
            child: Padding(
              padding: const EdgeInsets.fromLTRB(
                16,
                16,
                16,
                90,
              ), // Alt kısımdan 90 boşluk bıraktık
              child: FutureBuilder<List<MoodData>>(
                future: _future,
                builder: (context, snapshot) {
                  if (!snapshot.hasData)
                    return const Center(child: CircularProgressIndicator());
                  final data = snapshot.data!;
                  return SingleChildScrollView(
                    child: Column(
                      children: [
                        RangeSelector(
                          selectedRange: _range,
                          onRangeSelected: (r) => setState(() {
                            _range = r;
                            _load();
                          }),
                        ),
                        const SizedBox(height: 12),
                        MoodLineChart(
                          data: data,
                          range: _range,
                          isDark: isDark,
                        ),
                        const SizedBox(height: 16),
                        MoodBarChart(data: data, range: _range, isDark: isDark),
                        const SizedBox(height: 16),
                        Text(
                          'This data was generated by AI based on your daily analysis.',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: isDark ? Colors.white70 : Colors.black54,
                            fontSize: 13,
                          ),
                        ),
                      ],
                    ),
                  );
                },
              ),
            ),
          ),
          const MoodGraphBottomNav(), // Navigation Bar Eklendi
        ],
      ),
    );
  }
}
